
#http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#search multipart
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/save?useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: estationznp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
#    static-locations: file:C://temp/, C://Users//Administrator//Desktop//save//src//main//resources//static/
    static-locations: file:C://Users//Administrator//Desktop//save//src//main//resources//static/
#    static-locations: classpath:templates/
#    C:\Users\Administrator\Desktop\save\src\main\resources\static
server:
  port: 8000

